[window]
opacity = 0.9

padding.x = 0
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[env]
TERM = "xterm-256color"

[font]
normal.family = "IosevkaTerm Nerd Font"
bold.family = "IosevkaTerm Nerd Font"
italic.family = "IosevkaTerm Nerd Font"
bold_italic.family = "IosevkaTerm Nerd Font"
size = 18

[general]
import = [
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/gruvbox.toml"
  "~/.config/alacritty/kaganawa-dragon.toml"
]

