import = [
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/gruvbox.toml"
]

[window]
opacity = 1

[env]
TERM = "xterm-256color"

[font]
normal = { family = "0xProtoNerdFont", style = "Regular"}
bold = { family = "0xProtoNerdFont", style = "Bold"}
italic = { family = "0xProtoNerdFont", style = "Italic"}
bold_italic = { family = "0xProtoNerdFont", style = "Bold Italic"}
size = 14.0
