#!/bin/bash

DOTFILES_REPO="https://github.com/Jorgedavyd/.dotfiles.git"
DOTFILES_DIR="$HOME/.dotfiles"

installBashEnv() {
    git clone https://github.com/ohmybash/oh-my-bash.git ~/.oh-my-bash
    chsh -s /bin/bash
    source $HOME/.bashrc
};

installAGS() {
    git clone https://github.com/aylur/astal $HOME/builds && cd $HOME/builds/astal/lang/gjs
    meson setup --prefix /usr build
    meson install -C build
    git clone https://github.com/aylur/ags.git $HOME/builds && $HOME/builds/ags
    go install -ldflags "\
        -X 'main.gtk4LayerShell=$(pkg-config --variable=libdir gtk4-layer-shell-0)/libgtk4-layer-shell.so' \
        -X 'main.astalGjs=$(pkg-config --variable=srcdir astal-gjs)'"
    sudo mv $GOPATH/bin/ags /usr/bin/ags
};

installSwww() {
    git clone https://github.com/LGFae/swww.git $HOME/builds && cd swww
    cargo build --release
    sudo mv target/release/swww /usr/local/bin
    sudo mv target/release/swww-daemon /usr/local/bin
};

installDependencies() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if command -v apt-get &> /dev/null; then
            ## update repos
            sudo apt-get update
            ## Setup the repos
            sudo add-apt-repository universe ## for hyprland
            sudo apt-get install software-properties-common ## for nvim
            sudo add-apt-repository -y ppa:neovim-ppa/stable ## for nvim
            ## install the per-repo programs
            sudo apt-get install -y python3 ripgrep curl wget tmux sed hyprland neovim neofetch go
            ## requirements for swww
            sudo apt-get update && sudo apt-get install -y python3 python3-pip
            pip install meson
            ## install the per-repo programs
            sudo apt-get update && sudo apt-get upgrade -y
        elif command -v pacman &> /dev/null; then
            sudo pacman -Syu --noconfirm ripgrep fzf tmux neovim sed go hyrpland
            ## requirements for swww
            sudo pacman -Syu --noconfirm python python-pip
        else
            echo "Not a valid package manager"
            exit 1
        fi
        installAGS
        installSwww

    else
        echo "Operating system not supported."
        exit 1
    fi
};

link_dotfiles() {
    mkdir -p "$HOME/.config"
    ln -sf "$DOTFILES_DIR/bash/.bashrc" "$HOME"
    ln -sf "$DOTFILES_DIR/bash/.bash_profile" "$HOME"
    ln -sf "$DOTFILES_DIR/nvim" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/ghostty" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/tmux" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/scripts" "$HOME/.local/"
    ln -sf "$DOTFILES_DIR/hypr" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/neofetch" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/swww" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/ags" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/zathura" "$HOME/.config/"
    ln -sf "$DOTFILES_DIR/fonts" "$HOME/.local/share/"
};

main() {
    installDependencies
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR" || { echo "Failed to clone dotfiles repo."; exit 1; }
    chmod +x "$DOTFILES_DIR/scripts/*"
    link_dotfiles
    installBashEnv
}

main
