#!/usr/bin/env bash

[[ -z $1 ]] && selected=$(find ~/projects ~/.dotfiles ~/oym -type d -name '*.git' ! -path '*tmux*' -exec dirname {} + | fzf) || selected="$1"
[[ -z $selected || ! -d $selected ]] && exit 0
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    tmux send-keys -t $selected_name 'vi .' C-m
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    tmux send-keys -t $selected_name 'vi .' C-m
fi

if [[ -z "$TMUX" ]]; then
    tmux attach-session -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi

